Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -77,11 +77,11 @@ run_regression_tests_job: #Test_&_send:
     - whoami
     - chmod +x ./send_results.sh
     - >
-      if [ -z "$TEST_NAME" ]; then
-        echo "run specific test"
-        mvn test -Dtest=$TEST_NAME || echo "[ERROR] Выполнение тестов завершилось с ошибкой"
-      else
+      if [ $TEST_NAME == null ]; then
         echo "run testng"
         mvn test -Dsurefire.suiteXmlFiles=testng.xml || echo "[ERROR] Выполнение тестов завершилось с ошибкой"
+      else
+        echo "run specific test"
+        mvn test -Dtest=$TEST_NAME || echo "[ERROR] Выполнение тестов завершилось с ошибкой"
       fi
     - ./send_results.sh || echo "[ERROR] Отправка результатов в Allure завершилась с ошибкой"
