Update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -76,5 +76,10 @@ run_regression_tests_job: #Test_&_send:
     - echo $RUN_TYPE
     - whoami
     - chmod +x ./send_results.sh
-    - mvn test -Dsurefire.suiteXmlFiles=testng.xml || echo "[ERROR] Выполнение тестов завершилось с ошибкой"
+    - >
+      if [ -z "$TEST_NAME" ]; then
+        mvn test -Dtest=$TEST_NAME || echo "[ERROR] Выполнение тестов завершилось с ошибкой"
+      else
+        mvn test -Dsurefire.suiteXmlFiles=testng.xml || echo "[ERROR] Выполнение тестов завершилось с ошибкой"
+      fi
     - ./send_results.sh || echo "[ERROR] Отправка результатов в Allure завершилась с ошибкой"
